#!/bin/bash

# Script para desplegar la aplicación en AWS App Runner
# Uso: ./deploy.sh

echo "==================================="
echo "Deployment Guide - AWS App Runner"
echo "==================================="
echo ""
echo "Paso 1: Preparar el Dockerfile"
echo "✓ Ya existe en c:\Users\Caritas\Documents\vscodev2\my-app\Dockerfile"
echo ""

echo "Paso 2: Build local del Docker (OPCIONAL - para testing)"
echo "$ docker build -t mi-app:latest ."
echo ""

echo "Paso 3: Crear repositorio en AWS ECR"
echo "$ aws ecr create-repository --repository-name acogida-app --region us-east-1"
echo ""

echo "Paso 4: Tag y push de la imagen a ECR"
echo "$ aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com"
echo "$ docker tag mi-app:latest <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/acogida-app:latest"
echo "$ docker push <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/acogida-app:latest"
echo ""

echo "Paso 5: Crear App Runner Service"
echo "1. Ir a AWS Console > App Runner"
echo "2. Click 'Create service'"
echo "3. Seleccionar 'Container Registry'"
echo "4. URI de imagen: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/acogida-app:latest"
echo "5. Port: 8080"
echo ""

echo "Paso 6: Configurar variables de entorno"
echo "En AWS App Runner, agregar las siguientes variables de entorno:"
echo "  MYSQL_HOST=<tu-rds-endpoint>"
echo "  MYSQL_PORT=3306"
echo "  MYSQL_USER=admin"
echo "  MYSQL_PASSWORD=<tu-password>"
echo "  MYSQL_DATABASE=acogida"
echo "  JWT_SECRET=<generado-aleatorio>"
echo "  PORT=8080"
echo "  NODE_ENV=production"
echo ""

echo "Paso 7: Inicializar la base de datos"
echo "Conectar a la BD de AWS RDS y ejecutar:"
echo "$ npm run init-db"
echo "$ npm run update-admin-password"
echo ""

echo "Paso 8: Actualizar la URL del frontend en Amplify"
echo "En AWS Amplify, una vez el App Runner esté corriendo:"
echo "  1. Build settings > Frontend"
echo "  2. Asegurar que está sirviendo desde App Runner"
echo ""

echo "==================================="
echo "Alternativa: Desplegar en EC2"
echo "==================================="
echo ""
echo "Si prefieres EC2 en lugar de App Runner:"
echo ""
echo "1. Conectar a EC2:"
echo "   $ ssh -i key.pem ec2-user@your-instance"
echo ""
echo "2. Instalar Node.js y git:"
echo "   $ sudo yum update -y"
echo "   $ curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -"
echo "   $ sudo yum install -y nodejs"
echo "   $ sudo yum install -y git"
echo ""
echo "3. Clonar repositorio:"
echo "   $ git clone <tu-repo> app"
echo "   $ cd app/server"
echo "   $ npm install"
echo ""
echo "4. Crear .env con credenciales de RDS"
echo ""
echo "5. Instalar PM2:"
echo "   $ sudo npm install -g pm2"
echo "   $ npm run init-db"
echo "   $ pm2 start server.js --name 'api-server'"
echo "   $ pm2 startup"
echo "   $ pm2 save"
echo ""
echo "6. Configurar security group para permitir puerto 3000/8080"
echo ""
echo "==================================="
